name: ev_charge
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3 # Add this line
  google_maps_flutter: ^2.9.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  location: ^5.0.0
  connectivity_plus: ^2.3.0
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  cloudinary_public: ^0.23.1
  khalti_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
